### ISSUE TITLE
A question about the use of the SDTrimsp program

### ISSUE THREAD

**Issue by Bwlin** [psszabo/SDTrimSP-GUI#1]
Dear Author:
I am very impressed and happy that you can share your source code, which is very beneficial to the progress of academic exchanges.
I have a problem, when I use the program, I feel that some files are missing and I don't see the " main SDTrimSP folder (which contains the subfolders "bin", "case", "doc", etc.) and the SDTrimSP binary (located f.e. "SDTrimSP_6.01/bin/linux.SEQ/"", I hope you can help me.

**Comment by psszabo** [comment]
Hi, 

thank you for the interest and for reaching out!

That part is missing because the repo only contains the GUI companion to the SDTrimSP code. SDTrimSP has to be licensed from the Max Planck Institute for Plasma Physics. This is free and mostly not complicated. You can contact Andreas Mutzke for getting the SDTrimSP code.

Best,
Paul Szabo

**Comment by psszabo** [comment]
I added a contact address (sdtrimsp@ipp.mpg.de) for acquiring the SDTrimSP code, I hope this resolves the issue.
